package DiemDanh;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LongTran
 */
public class CapNhatTheSV extends javax.swing.JFrame {
    private String MS;
    QuanLiSinhVien q;
    private Connection con = null;
    QuanLiSinhVien ql = new QuanLiSinhVien();
    /**
     * Creates new form CapNhatThe
     */
    public CapNhatTheSV() {
        initComponents();
    }
    
    public CapNhatTheSV(QuanLiSinhVien q, String MS) {
        initComponents();
        this.q = q;
        this.MS = MS;
        System.out.println(MS);
        txtMaT.setDocument(new LengthRestrictedDocument(10));
        txtMaT.requestFocusInWindow();
        txtMaT.requestFocus();
        txtMaT.addActionListener( action );
    }
    String NUMBER_REGEX = "^[0-9]+$";
    Action action = new AbstractAction(){
    @Override
        public void actionPerformed(ActionEvent e){
            if(!txtMaT.getText().equals("")){
                if(txtMaT.getText().matches(NUMBER_REGEX)){
                String sql2 = "select * from sinhvien where MaRFID = ?";
                    try{
                   con = Connect.connect();
                   PreparedStatement pst2 = con.prepareStatement(sql2);
                   pst2.setString(1,txtMaT.getText());

                   ResultSet rs2 = pst2.executeQuery();
                   if(rs2.next()){
                       JOptionPane.showMessageDialog(null, "Mã RFID đã tồn tại!!");
                   }else{
                         String sql1 = "select * from canbo where MaRFID = ?";
                           try{
                           con = Connect.connect();
                           PreparedStatement pst1 = con.prepareStatement(sql1);
                           pst1.setString(1,txtMaT.getText());
                           ResultSet rs1 = pst1.executeQuery();
                           if(rs1.next()){
                               JOptionPane.showMessageDialog(null, "Mã RFID đã tồn tại!!");
                           }else{
                                    ql.clearTable();
                                    Sua();
                                    ql.loadTable();
                                    dispose(); 
                                    JOptionPane.showMessageDialog(null, "Cập nhật thành công!");
                                    dispose(); 
                                }
                        }catch (Exception ex) {
                             JOptionPane.showMessageDialog(null, "Kết nối cơ sở dũ liệu thất bại!! :(");
                         }
                        }
               }catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Kết nối cơ sở dũ liệu thất bại!! :(");
                }
                }else{
                    JOptionPane.showMessageDialog(null, "Mã RFID không hợp lệ");
                }
        }
        }
    };
    
    private void Sua(){
        try {
            con = Connect.connect();
            Statement st = con.createStatement();
            String MaT = txtMaT.getText();
            String suKien = "Update sinhvien set MaRFID = '"+MaT+"' where MSSV = '"+MS+"'";
            st.executeUpdate(suKien);
            con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMaT = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Thêm mã thẻ");

        txtMaT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMaT.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaT, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnHuy, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapNhatTheSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapNhatTheSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapNhatTheSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapNhatTheSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapNhatTheSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtMaT;
    // End of variables declaration//GEN-END:variables
}
