/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DiemDanh;

/**
 *
 * @author trana
 */
public class ChonSK extends javax.swing.JPanel {

    /**
     * Creates new form ChonSK
     */
    public ChonSK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(1060, 511));
        setPreferredSize(new java.awt.Dimension(1060, 511));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách sự kiện đang diễn ra");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(5, 5));

        jButton1.setText("<html> <center><b style=\"color:red; font-size:16\">Ngày Hội Việc Làm</b> <br> <p>7:00 đến 11:00</p></center> </html>");
        jPanel2.add(jButton1);

        jButton2.setText("<html> <center><b style=\"color:red; font-size:16\">Ngày Hội Việc Làm</b> <br> <p>7:00 đến 11:00</p></center> </html>");
        jPanel2.add(jButton2);

        jButton3.setText("<html> <center><b style=\"color:red; font-size:16\">Ngày Hội Việc Làm</b> <br> <p>7:00 đến 11:00</p></center> </html>");
        jPanel2.add(jButton3);

        jButton4.setText("<html> <center><b style=\"color:red; font-size:16\">Ngày Hội Việc Làm</b> <br> <p>7:00 đến 11:00</p></center> </html>");
        jPanel2.add(jButton4);

        jButton5.setText("<html> <center><b style=\"color:red; font-size:16\">Ngày Hội Việc Làm</b> <br> <p>7:00 đến 11:00</p></center> </html>");
        jPanel2.add(jButton5);

        jButton6.setText("<html> <center><b style=\"color:red; font-size:16\">Ngày Hội Việc Làm</b> <br> <p>7:00 đến 11:00</p></center> </html>");
        jPanel2.add(jButton6);

        jButton7.setText("<html> <center><b style=\"color:red; font-size:16\">Ngày Hội Việc Làm</b> <br> <p>7:00 đến 11:00</p></center> </html>");
        jPanel2.add(jButton7);

        jButton8.setText("<html> <center><b style=\"color:red; font-size:16\">Ngày Hội Việc Làm</b> <br> <p>7:00 đến 11:00</p></center> </html>");
        jPanel2.add(jButton8);

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
