/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DiemDanh;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author trana
 */
public class SuaTTCb extends javax.swing.JFrame {

    /**
     * Creates new form SuaSK
     */
    public SuaTTCb() {
        initComponents();
        txtMa.setEditable(false);
        txtMaT.setDocument(new LengthRestrictedDocument(10));
        System.out.println("Sửa tt cán bộ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbbKhoa = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtMaT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbbNganh = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtEM = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sửa thông tin sinh viên");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã số cán bộ:");
        jLabel2.setToolTipText("");

        txtMa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Họ tên:");

        txtHoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tạo Cán Bộ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Khoa:");

        cbbKhoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khoa Công nghệ", "Khoa Công nghệ TT-TT", "Khoa Khoa học Chính trị", "Khoa Khoa học Tự nhiên", "Khoa Khoa học Xã hội & Nhân văn", "Khoa Kinh tế", "Khoa Luật", "Khoa Môi trường & TNTN", "Khoa Nông nghiệp & SHƯD", "Khoa Ngoại ngữ", "Khoa Phát triển Nông thôn", "Khoa Sư phạm", "Khoa Thủy sản", "Viện NC&PTCNSH", "Viện NCPT ĐBSCL", "Bộ môn Giáo dục Thể chất" }));
        cbbKhoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbKhoaItemStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Mã số thẻ:");

        txtMaT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Ngành:");
        jLabel12.setToolTipText("");

        cbbNganh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbNganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công nghệ kỹ thuật hóa học", "Công nghệ kỹ thuật hóa học (Chất lượng cao)", "Kỹ thuật điều khiển và tự động hóa", "Kỹ thuật điện tử, truyền thông", "Kỹ thuật điện, điện tử (Kỹ thuật điện)", "Kỹ thuật công trình thủy", "Kỹ thuật công trình xây dựng (XD Công trình thủy)", "Kỹ thuật công trình xây dựng (XD cầu đường)", "Kỹ thuật công trình xây dựng (XD dân dụng và CN)", "Kỹ thuật cơ - điện tử", "Kỹ thuật cơ khí (Cơ khí chế biến)", "Kỹ thuật cơ khí (Cơ khí chế tạo máy)", "Kỹ thuật cơ khí (Cơ khí giao thông)", "Kỹ thuật Máy tính", "Kỹ thuật vật liệu", "Kỹ thuật xây dựng công trình giao thông", "Quản lý công nghiệp" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Email:");

        txtEM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnHuy.setBackground(new java.awt.Color(51, 153, 255));
        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnLuu.setBackground(new java.awt.Color(51, 153, 255));
        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEM, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbNganh, 0, 272, Short.MAX_VALUE)
                            .addComponent(cbbKhoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txtMaT)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addGap(0, 235, Short.MAX_VALUE))
                    .addComponent(txtMa))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btnLuu)
                .addGap(18, 18, 18)
                .addComponent(btnHuy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5)
                    .addContainerGap(207, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbbNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLuu)
                    .addComponent(btnHuy))
                .addGap(33, 33, 33))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5)
                    .addContainerGap(355, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    String NUMBER_REGEX = "^[0-9]+$";
    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        QuanLiCanBo ql = new QuanLiCanBo();
        if(txtHoTen.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Họ và tên cán bộ không được trống!");
        }else{
            if(txtEM.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Email không được trống!");
            }else if(!txtEM.getText().matches(EMAIL_REGEX)){
                    JOptionPane.showMessageDialog(null, "Email không hợp lệ!");
                }else{
                if(!txtMaT.getText().equals("")){
                    if(txtMaT.getText().matches(NUMBER_REGEX)){
                    String sql = "select * from sinhvien where MaRFID = ?";
                    try{
                    con = Connect.connect();
                    PreparedStatement pst = con.prepareStatement(sql);
                    pst.setString(1,txtMaT.getText());

                    ResultSet rs = pst.executeQuery();
                    if(rs.next()){
                        JOptionPane.showMessageDialog(null, "Mã RFID đã tồn tại!!");
                    }else{
                                String sql1 = "select * from canbo where MaRFID = ?";
                        try{
                           con = Connect.connect();
                           PreparedStatement pst1 = con.prepareStatement(sql1);
                           pst1.setString(1,txtMaT.getText());
                           ResultSet rs1 = pst1.executeQuery();
                           if(rs1.next()){
                               JOptionPane.showMessageDialog(null, "Mã RFID đã tồn tại!!");
                           }else{
                                ql.clearTable();
                                Sua();
                                ql.loadTable();
                                this.dispose(); 
                                JOptionPane.showMessageDialog(null, "Sửa dữ liệu thành công!");
                                this.dispose(); 
                                }

                       } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, "Kết nối cơ sở dũ liệu thất bại!! :(");
                        } 
                        }
                       
                }catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Kết nối cơ sở dũ liệu thất bại!! :(");
                }
                }else{
                        JOptionPane.showMessageDialog(null, "Mã RFID không hợp lệ");
                    }
                }else{
                    ql.clearTable();
                    Sua();
                    ql.loadTable();
                    this.dispose(); 
                    JOptionPane.showMessageDialog(null, "Sửa dữ liệu thành công!");
                    this.dispose();
                }
        }
                
            
            }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void cbbKhoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbKhoaItemStateChanged
        nganhKhoa();
    }//GEN-LAST:event_cbbKhoaItemStateChanged

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        int n = JOptionPane.showConfirmDialog(null,"Bạn chắc chắn muốn hủy?","THÔNG BÁO",JOptionPane.YES_NO_OPTION);
        if(n == JOptionPane.YES_OPTION){
            this.dispose();
        }else 
            return;
    }//GEN-LAST:event_btnHuyActionPerformed

    
    private void nganhKhoa(){
        if(cbbKhoa.getSelectedItem().equals("Khoa Công nghệ")){
            cbbNganh.removeAllItems();
            cbbNganh.addItem("Công nghệ kỹ thuật hóa học");
            cbbNganh.addItem("Công nghệ kỹ thuật hóa học (Chất lượng cao)");
            cbbNganh.addItem("Kỹ thuật điều khiển và tự động hóa");
            cbbNganh.addItem("Kỹ thuật điện tử, truyền thông");
            cbbNganh.addItem("Kỹ thuật điện, điện tử (Kỹ thuật điện)");
            cbbNganh.addItem("Kỹ thuật công trình thủy");
            cbbNganh.addItem("Kỹ thuật công trình xây dựng (XD Công trình thủy)");
            cbbNganh.addItem("Kỹ thuật công trình xây dựng (XD cầu đường)");
            cbbNganh.addItem("Kỹ thuật công trình xây dựng (XD dân dụng và CN)");
            cbbNganh.addItem("Kỹ thuật cơ - điện tử");
            cbbNganh.addItem("Kỹ thuật cơ khí (Cơ khí chế biến)");
            cbbNganh.addItem("Kỹ thuật cơ khí (Cơ khí chế tạo máy)");
            cbbNganh.addItem("Kỹ thuật cơ khí (Cơ khí giao thông)");
            cbbNganh.addItem(("Kỹ thuật Máy tính"));
            cbbNganh.addItem("Kỹ thuật vật liệu");
            cbbNganh.addItem("Kỹ thuật xây dựng công trình giao thông");
            cbbNganh.addItem("Quản lý công nghiệp");
        }else if(cbbKhoa.getSelectedItem().equals("Khoa Công nghệ TT-TT")){
            cbbNganh.removeAllItems();
            cbbNganh.addItem("Công nghệ thông tin");
            cbbNganh.addItem("Công nghệ thông tin (Chât lượng cao)");
            cbbNganh.addItem("Công nghệ thông tin (Tin học ứng dụng)");
            cbbNganh.addItem("Hệ thống thông tin");
            cbbNganh.addItem("Kỹ thuật phần mềm");
            cbbNganh.addItem("Khoa học máy tính");
            cbbNganh.addItem("Truyền thông và Mạng máy tính");
        }else if(cbbKhoa.getSelectedItem().equals("Khoa Khoa học Chính trị")){
            cbbNganh.removeAllItems();
            cbbNganh.addItem("Chính trị học");
            cbbNganh.addItem("Giáo dục công dân");
            cbbNganh.addItem("Triết học");
        }else if(cbbKhoa.getSelectedItem().equals("Khoa Khoa học Tự nhiên")){
            cbbNganh.removeAllItems();
            cbbNganh.addItem("Hóa dược");
            cbbNganh.addItem("Hóa học");
            cbbNganh.addItem("Hóa học (Hóa dược)");
            cbbNganh.addItem("Sinh học");
            cbbNganh.addItem("Toán ứng dụng");
            cbbNganh.addItem("Vật lý kỹ thuật");
        }else if(cbbKhoa.getSelectedItem().equals("Khoa Khoa học Xã hội & Nhân văn")){
            cbbNganh.removeAllItems();
            cbbNganh.addItem("Thông tin học");
            cbbNganh.addItem("Văn học");
            cbbNganh.addItem("Việt Nam học (Hướng dẫn viên du lịch)");
            cbbNganh.addItem("Xã hội học");
        }else if(cbbKhoa.getSelectedItem().equals("Khoa Kinh tế")){
            cbbNganh.removeAllItems();
            cbbNganh.addItem("Kế toán");
            cbbNganh.addItem("Kiểm toán");
            cbbNganh.addItem("Kinh doanh quốc tế");
            cbbNganh.addItem("Kinh doanh quốc tế (Chất lượng cao)");
            cbbNganh.addItem("Kinh doanh thương mại");
            cbbNganh.addItem("Kinh tế");
            cbbNganh.addItem("Kinh tế nông nghiệp");
            cbbNganh.addItem("Kinh tế tài nguyên thiên nhiên");
            cbbNganh.addItem("Marketing");
            cbbNganh.addItem("Quản trị dịch vụ du lịch và lữ hành");
            cbbNganh.addItem("Quản trị kinh doanh");
            cbbNganh.addItem("Tài chính - Ngân hàng");
        }else if(cbbKhoa.getSelectedItem().equals("Khoa Luật")){
            cbbNganh.removeAllItems();
            cbbNganh.addItem("Luật (Luật Hành chính)");
            cbbNganh.addItem("Luật (Luật Thương mại)");
            cbbNganh.addItem("Luật (Luật Tư pháp)");
        }else if(cbbKhoa.getSelectedItem().equals("Khoa Môi trường & TNTN")){
            cbbNganh.removeAllItems();
            cbbNganh.addItem("Kỹ thuật môi trường");
            cbbNganh.addItem("Kỹ thuật tài nguyên nước");
            cbbNganh.addItem("Khoa học môi trường");
            cbbNganh.addItem("Lâm sinh"); 
            cbbNganh.addItem("Quản lý đất đai");
            cbbNganh.addItem("Quản lý tài nguyên và môi trường");
        }else if(cbbKhoa.getSelectedItem().equals("Khoa Nông nghiệp & SHƯD")){
            cbbNganh.removeAllItems();
            cbbNganh.addItem("Bảo vệ thực vật");
            cbbNganh.addItem("Công nghệ rau hoa quả và cảnh quan");
            cbbNganh.addItem("Công nghệ sau thu hoạch");
            cbbNganh.addItem("Công nghệ thực phẩm");
            cbbNganh.addItem("Chăn nuôi");
            cbbNganh.addItem("Khoa học đất");
            cbbNganh.addItem("Khoa học cây trồng");
            cbbNganh.addItem("Khoa học cây trồng (Công nghệ giống cây trồng)");
            cbbNganh.addItem("Nông học");
            cbbNganh.addItem("Sinh học ứng dụng");
            cbbNganh.addItem("Thú y");
            cbbNganh.addItem("Thú y (Dược Thú y)");
        }else if(cbbKhoa.getSelectedItem().equals("Khoa Ngoại ngữ")){
            cbbNganh.removeAllItems();
            cbbNganh.addItem("Ngôn ngữ Anh");
            cbbNganh.addItem("Ngôn ngữ Anh (Phiên dịch - Biên dịch tiếng Anh)");
            cbbNganh.addItem("Ngôn ngữ Pháp");
            cbbNganh.addItem("Sư Phạm Tiếng Anh");
            cbbNganh.addItem("Sư phạm Tiếng Pháp");
        }else if(cbbKhoa.getSelectedItem().equals("Khoa Phát triển Nông thôn")){
            cbbNganh.removeAllItems();
            cbbNganh.addItem("Khuyến nông");
            cbbNganh.addItem("Kinh doanh nông nghiệp");
            cbbNganh.addItem("Nông học (Kỹ thuật nông nghiệp)");
        }else if(cbbKhoa.getSelectedItem().equals("Khoa Sư phạm")){
            cbbNganh.removeAllItems();
            cbbNganh.addItem("Giáo dục Tiểu học");
            cbbNganh.addItem("Sư phạm Địa lý");
            cbbNganh.addItem("Sư phạm Hóa học");
            cbbNganh.addItem("Sư phạm Lịch sử");
            cbbNganh.addItem("Sư Phạm Ngữ Văn");
            cbbNganh.addItem("Sư phạm Sinh học");
            cbbNganh.addItem("Sư phạm Tin học");
            cbbNganh.addItem("Sư phạm Toán học");
            cbbNganh.addItem("Sư phạm Vật lý");
            cbbNganh.addItem("Sư phạm Vật lý (Vật lý - Tin học)");
        }else if(cbbKhoa.getSelectedItem().equals("Khoa Thủy sản")){
            cbbNganh.removeAllItems();
            cbbNganh.addItem("Bệnh học thủy sản");
            cbbNganh.addItem("Công nghệ chế biến thủy sản");
            cbbNganh.addItem("Kinh tế nông nghiệp (Kinh tế thủy sản)");
            cbbNganh.addItem("Nuôi trồng thủy sản");
            cbbNganh.addItem("Nuôi trồng thủy sản (Chương trình tiên tiến)");
            cbbNganh.addItem("Quản lý nguồn lợi thủy sản");
        }else if(cbbKhoa.getSelectedItem().equals("Viện NC&PTCNSH")){
            cbbNganh.removeAllItems();
            cbbNganh.addItem("Công nghệ Sinh học");
            cbbNganh.addItem("Công nghệ sinh học (Chương trình tiên tiến)");
            cbbNganh.addItem("Sinh học (Vi sinh vật học)");
        }else if(cbbKhoa.getSelectedItem().equals("Viện NCPT ĐBSCL")){
            cbbNganh.removeAllItems();
            cbbNganh.addItem("Phát triển nông thôn");
        }else if(cbbKhoa.getSelectedItem().equals("Bộ môn Giáo dục Thể chất")){
            cbbNganh.removeAllItems();
            cbbNganh.addItem("Giáo dục thể chất");
        }
    }
    private Connection con = null;
    
    private void Sua(){
        try {
            con = Connect.connect();
            Statement st = con.createStatement();
            String Ma = txtMa.getText();
            String HoTen = txtHoTen.getText();
            String Em = txtEM.getText();
            String Khoa = (String) cbbKhoa.getSelectedItem();
            String Nganh = (String) cbbNganh.getSelectedItem();
            String MaT = txtMaT.getText();
            String suKien = "Update canbo set HoTen = '"+HoTen+"',Email = '"+Em+"', MaRFID = '"+MaT+"', BoMon_To = '"+Nganh+"', Khoa_Phong = '"+Khoa+"' where MSCB = '"+Ma+"'";
            st.executeUpdate(suKien);
            con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
                                          

                                  

    String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
                          
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaTTCb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaTTCb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaTTCb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaTTCb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaTTCb().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    public javax.swing.JComboBox<String> cbbKhoa;
    public javax.swing.JComboBox<String> cbbNganh;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JTextField txtEM;
    public javax.swing.JTextField txtHoTen;
    public javax.swing.JTextField txtMa;
    public javax.swing.JTextField txtMaT;
    // End of variables declaration//GEN-END:variables
}
